package com.asecurity.esbdb;
// Generated 20.04.2015 14:11:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApacseventsCha generated by hbm2java
 */
@Entity
@Table(name="apacsevents_cha"
    ,schema="public"
)
public class ApacseventsCha  implements java.io.Serializable {


     private String eventid;
     private String eventtype;
     private String eventtypedesc;
     private String holderid;
     private String holdername;
     private String holdershortname;
     private String sourceid;
     private String sourcename;
     private String eventtime;
     private String messagexml;
     private String messageid;
     private String messagetime;

    public ApacseventsCha() {
    }

	
    public ApacseventsCha(String eventid) {
        this.eventid = eventid;
    }
    public ApacseventsCha(String eventid, String eventtype, String eventtypedesc, String holderid, String holdername, String holdershortname, String sourceid, String sourcename, String eventtime, String messagexml, String messageid, String messagetime) {
       this.eventid = eventid;
       this.eventtype = eventtype;
       this.eventtypedesc = eventtypedesc;
       this.holderid = holderid;
       this.holdername = holdername;
       this.holdershortname = holdershortname;
       this.sourceid = sourceid;
       this.sourcename = sourcename;
       this.eventtime = eventtime;
       this.messagexml = messagexml;
       this.messageid = messageid;
       this.messagetime = messagetime;
    }
   
     @Id 

    
    @Column(name="eventid", unique=true, nullable=false)
    public String getEventid() {
        return this.eventid;
    }
    
    public void setEventid(String eventid) {
        this.eventid = eventid;
    }

    
    @Column(name="eventtype")
    public String getEventtype() {
        return this.eventtype;
    }
    
    public void setEventtype(String eventtype) {
        this.eventtype = eventtype;
    }

    
    @Column(name="eventtypedesc")
    public String getEventtypedesc() {
        return this.eventtypedesc;
    }
    
    public void setEventtypedesc(String eventtypedesc) {
        this.eventtypedesc = eventtypedesc;
    }

    
    @Column(name="holderid")
    public String getHolderid() {
        return this.holderid;
    }
    
    public void setHolderid(String holderid) {
        this.holderid = holderid;
    }

    
    @Column(name="holdername")
    public String getHoldername() {
        return this.holdername;
    }
    
    public void setHoldername(String holdername) {
        this.holdername = holdername;
    }

    
    @Column(name="holdershortname")
    public String getHoldershortname() {
        return this.holdershortname;
    }
    
    public void setHoldershortname(String holdershortname) {
        this.holdershortname = holdershortname;
    }

    
    @Column(name="sourceid")
    public String getSourceid() {
        return this.sourceid;
    }
    
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid;
    }

    
    @Column(name="sourcename")
    public String getSourcename() {
        return this.sourcename;
    }
    
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename;
    }

    
    @Column(name="eventtime")
    public String getEventtime() {
        return this.eventtime;
    }
    
    public void setEventtime(String eventtime) {
        this.eventtime = eventtime;
    }

    
    @Column(name="messagexml")
    public String getMessagexml() {
        return this.messagexml;
    }
    
    public void setMessagexml(String messagexml) {
        this.messagexml = messagexml;
    }

    
    @Column(name="messageid")
    public String getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

    
    @Column(name="messagetime")
    public String getMessagetime() {
        return this.messagetime;
    }
    
    public void setMessagetime(String messagetime) {
        this.messagetime = messagetime;
    }




}


